// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	optimus "github.com/odpf/optimus/api/proto/odpf/optimus/core/v1beta1"
)

// RuntimeService_DeployJobSpecificationServer is an autogenerated mock type for the RuntimeService_DeployJobSpecificationServer type
type RuntimeService_DeployJobSpecificationServer struct {
	mock.Mock
}

// Context provides a mock function with given fields:
func (_m *RuntimeService_DeployJobSpecificationServer) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Recv provides a mock function with given fields:
func (_m *RuntimeService_DeployJobSpecificationServer) Recv() (*optimus.DeployJobSpecificationRequest, error) {
	ret := _m.Called()

	var r0 *optimus.DeployJobSpecificationRequest
	if rf, ok := ret.Get(0).(func() *optimus.DeployJobSpecificationRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*optimus.DeployJobSpecificationRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecvMsg provides a mock function with given fields: m
func (_m *RuntimeService_DeployJobSpecificationServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: _a0
func (_m *RuntimeService_DeployJobSpecificationServer) Send(_a0 *optimus.DeployJobSpecificationResponse) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*optimus.DeployJobSpecificationResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendHeader provides a mock function with given fields: _a0
func (_m *RuntimeService_DeployJobSpecificationServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMsg provides a mock function with given fields: m
func (_m *RuntimeService_DeployJobSpecificationServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetHeader provides a mock function with given fields: _a0
func (_m *RuntimeService_DeployJobSpecificationServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *RuntimeService_DeployJobSpecificationServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}
